### ISSUE TITLE
Não entendi o menu do software [USUÁRIO COMUM]

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#1]
Bom dia, @guilhermezimmermann 

Gostaria de enviar uma observação, no qual Eu como usuário comum não entendi do que o software se trata, com o seguinte menu:

Choose a option: 

1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: 

List o que ?
Insert o que ?
Update o que ?
Delete o que ?
Exit o que?

Do que o software se trata?

Como utilizo?

Vou escolher opção para o que?

**Comment by Guilherme-Zimmermann** [comment]
Não entendi, necessita de explicação comentada no código, ou na saída do do console?

**Comment by alvessh** [comment]
> Não entendi, necessita de explicação comentada no código, ou na saída do do console?

Opa @guilhermezimmermann 

Estou falando do console em si, pense que Você desenvolve o software para quem utilizar?

Usuário final correto?

Agora se posicione como um usuário utilizando o teu software..

Ele vai conseguir usar?
Ele vai entender?

**Comment by guilhermezimmermann** [comment]
Pronto, existe mais alguma observação que necessita ser feita referente a isso?

**Comment by Guilherme-Zimmermann** [comment]
Pronto, existe mais alguma observação que necessita ser feita referente a isso?

**Comment by alvessh** [comment]
> Pronto, existe mais alguma observação que necessita ser feita referente a isso?

a opção "Digite (5) Para sair"

Poderia especificar melhor, Sair da onde???

**Comment by alvessh** [comment]
@guilhermezimmermann 

Show, porém 

Programa de Controle de tarefas
Escolha uma opção: 
```
Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair da aplicação
Você deseja: Ser Feliz
```
"Você deseja: " não é ideal aqui.

Eu desejo ser feliz... tlgado?

Não faz sentido, é interessante ajustar essa label.

**Comment by alvessh** [comment]
@guilhermezimmermann 

Poderia melhorar a listagem das tarefas?
Exemplo:

Id | Titulo | Decrição | Starus
1 - T1 - Tarefa 1 - Pedente
2 - T2 - Tarefa 3 - Completa

**Comment by alvessh** [comment]
Show
