### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant model.entities.enums.Status.Status

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#3]
1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: 2

Id for insert: 10
Title: Titulo
Description: Descricao
Status: Status
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant model.entities.enums.Status.Status
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at model.entities.enums.Status.valueOf(Status.java:1)
	at Application.main(Application.java:43)

Bom dia @guilhermezimmermann 

Segue o erro acima, ao tentar fazer Insert.

**Comment by guilhermezimmermann** [comment]
Isso resolve o seu problema?

**Comment by Guilherme-Zimmermann** [comment]
Isso resolve o seu problema?

**Comment by alvessh** [comment]
> Isso resolve o seu problema?


Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair
Você deseja: 3

Id da tarefa que deseja alterar: 2
Novo título: Novo Teste
Nova descrição: Nova ddescricao
Novo status: 1
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant model.entities.enums.Status.1
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at model.entities.enums.Status.valueOf(Status.java:1)
	at Application.main(Application.java:67)

**Comment by alvessh** [comment]
> > Isso resolve o seu problema?
> 
> Digite (1) Para listar todas suas tarefas Digite (2) Para inserir uma nova tarefa Digite (3) Para alterar uma tarefa Digite (4) Para deletar uma tarefa Digite (5) Para sair Você deseja: 3
> 
> Id da tarefa que deseja alterar: 2 Novo título: Novo Teste Nova descrição: Nova ddescricao Novo status: 1 Exception in thread "main" java.lang.IllegalArgumentException: No enum constant model.entities.enums.Status.1 at java.base/java.lang.Enum.valueOf(Enum.java:273) at model.entities.enums.Status.valueOf(Status.java:1) at Application.main(Application.java:67)

**Problema continua @guilhermezimmermann**

**Comment by Guilherme-Zimmermann** [comment]
Eu vi esse problema ai resolvendo outro kkk, resolvendo agora

**Comment by Guilherme-Zimmermann** [comment]
Resolvido
