### ISSUE TITLE
Substitiuir o item que Eu já tinha inserido

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#4]
Pedi para inserir e o sistema atualizou outro item que já tinha inserido.

1 - Title: Test 1
Description: TEste 1
Status: PENDING

1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: 2

Id for insert: 1
Title: Teste 2
Description: Teste 2
Status: PENDING

1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: 1

1 - Title: Teste 2
Description: Teste 2
Status: PENDING

1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: 

Bom dia, @guilhermezimmermann

**Comment by Guilherme-Zimmermann** [comment]
Esse problema já foi resolvido com o software inserindo o id da tarefa automaticamente

**Comment by alvessh** [comment]
> Esse problema já foi resolvido com o software inserindo o id da tarefa automaticamente

Obrigado!
