### ISSUE TITLE
Inserindo uma tarefa já como COMPLETA

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#6]
Você deseja: 2

Título da tarefa: Titulo 1
Descrição: Descricao 1
Digite (1) se a tarefa estiver PENDENTE
Digite (2) se a tarefa estiver COMPLETO
Status: 2

Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair
Você deseja: 1

1 - Id: 1
Título: Titulo 1
Descrição: Descricao 1
Status: COMPLETO

Boa tarde, @guilhermezimmermann 

Gostaria de tirar uma dúvida, se faz sentido a lógica de Eu inserir uma nova tarefa já como o status de "COMPLETA".

**Comment by Guilherme-Zimmermann** [comment]
Eu pensei a mesma coisa, mas foi somente para controle kkkkkkkk

**Comment by Guilherme-Zimmermann** [comment]
Eu pensei assim.
Digamos que eu tenha tarefas que eu já fiz, porém esqueci de inserir na lista, ai por questão de controle já posso inserir como completa.

**Comment by alvessh** [comment]
> 

Eu entendi, até que faz sentido essa opção, porém acho poderia ser uma ação separada, para poder liberar para pessoas autorizadas apenas entende.. se não posso inserir full tarefas completas e nem para controle, penso no futuro...
