### ISSUE TITLE
Digito a opção 5 para sair do sistema e o software me retorna mensagem de opção inválida

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#7]
Programa de Controle de tarefas
Escolha uma opção: 

Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair
Você deseja: 5
**Opção inválida, tente novamente!**

**Comment by Guilherme-Zimmermann** [comment]
Tente agora

**Comment by Guilherme-Zimmermann** [comment]
Resolvido
