### ISSUE TITLE
Solicitação do status em andamento e da opção para ir adicionando percentual 

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#8]
Boa tarde, @guilhermezimmermann 

Gostaria da opção para adicionar percentual da tarefa, e que ao listar aparecer com o Status "Em Andamento" e o percentual já concluido

**Comment by guilhermezimmermann** [comment]
Você gostaria de inserir a porcentagem já na criação da tarefa ou somente na alteração?

**Comment by alvessh** [comment]
Obrigado
